# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HIAGs3HOjqWyJ/xuOuCII2fM7u/eulHNtVzL/9b7hIdzIwqbHFgGyh+/GhqdwWKtV148NvkUS/1sdtE2xIvE89K4m8Rs/t1tKEexDJ3/v70PmM0DXnZ/lZ43aRqTo+jq2iFxPHGPXa15YR+/qPcukf5ABDsiQ+Y2a+VnvRRHtW6vaDrhaQ01DKinbyYyq5p3tFJWbxsShk3VlPteZYhMRjgAsOFkdq+fcQSvGBoRn54lQ7TlQtnIpNcz8BRwOPiR12Fs6YR9z2l+PxbQd7IhQlAl5Qfh2mBlwIvhiE71kscDs9EgRhAu06xHaihsMjRsWLNdxzqaGT367k2vJxcYopfFJVIvA5ca7sc/ork+BWID15OTBE7Gp5Pbs+IPh8tkUMRt0IXa43EEw3jNQ4ztSuEvyiIRpUNkLqvvtflh8UP0yCeAxDzFjP+fEmxY5Lh73RKb1l25HcV8NqD63H2ud4zX9rx7aMNXAuCppLP55Uns44+gGzN5ypU0MomgERmIqG6Z9VRTP8BUDG4xuye0UoqpoMqQYUEAdOkVmjpMgkyIWZuhzGg6V1qX0SewymL+FcoVxiq+PdOetYgBTI2QDMUqprnl00HxAYzbv3Sr2F+2qRlYEjMeZe/6YATMhsbX0e+3yaaVS2Jo2bXrXNv++Vidtv42oShxCRn0c2ifcN4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
