travis:
  secure:
    BINSTAR_TOKEN: HIAGs3HOjqWyJ/xuOuCII2fM7u/eulHNtVzL/9b7hIdzIwqbHFgGyh+/GhqdwWKtV148NvkUS/1sdtE2xIvE89K4m8Rs/t1tKEexDJ3/v70PmM0DXnZ/lZ43aRqTo+jq2iFxPHGPXa15YR+/qPcukf5ABDsiQ+Y2a+VnvRRHtW6vaDrhaQ01DKinbyYyq5p3tFJWbxsShk3VlPteZYhMRjgAsOFkdq+fcQSvGBoRn54lQ7TlQtnIpNcz8BRwOPiR12Fs6YR9z2l+PxbQd7IhQlAl5Qfh2mBlwIvhiE71kscDs9EgRhAu06xHaihsMjRsWLNdxzqaGT367k2vJxcYopfFJVIvA5ca7sc/ork+BWID15OTBE7Gp5Pbs+IPh8tkUMRt0IXa43EEw3jNQ4ztSuEvyiIRpUNkLqvvtflh8UP0yCeAxDzFjP+fEmxY5Lh73RKb1l25HcV8NqD63H2ud4zX9rx7aMNXAuCppLP55Uns44+gGzN5ypU0MomgERmIqG6Z9VRTP8BUDG4xuye0UoqpoMqQYUEAdOkVmjpMgkyIWZuhzGg6V1qX0SewymL+FcoVxiq+PdOetYgBTI2QDMUqprnl00HxAYzbv3Sr2F+2qRlYEjMeZe/6YATMhsbX0e+3yaaVS2Jo2bXrXNv++Vidtv42oShxCRn0c2ifcN4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
