appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Ml9sy1pGKpcMrYi2YnHY948ntCU8sVnSIvf3YE/iYtP4CDLNBtZiZOcZO7hxrge/nNxZlgeQ7KakzctZeuJhjdVbfiauqqVY8OtrN6t4W0aOzsrHg61Xx+/ETNhw1klrqaDaWMEV9L0SKlZ2ZOdfS12TG7y6T1NtgJjzoorvaM1GW2Qol5DVjYFHllEWxjkOELwYEIBFYe8u2pV4Psq+Zmvtd9XQNBbFsMqow3lPf7p/cXf8u0yULw8ugnvsjMNAdtNLL8Qbm8cg6SNHX6j8Wkxs1Gqk6OXPtC8wvI1RdvqlsABmLbt9svjHRWjNh10WF+jKYQu+19eWTR/ySnePu8D14cuuXuUPtg+cTLHyQlB4/s7+cKjsPPh18/CD4+obdzfvTV2Yijy68ySEJXMK1+HC1jkwWWZGds3w7BiFIS/L/CCIBV7RTF8OGCb3NTJbHaTfVmizWh4m7Khs1VYwi4qoKJHeXxeGo2OGs6zmeqgIHI5dzLUhXROXhezW97Iv0YhEnMPC7RKaYZQXRLjz3qazq1R5WgU/CfrbdD7EEsvrTX42ENFiF8BcW6UyQZr2sMuRA5PMmLra7WTAm3dsOYaCdTj4o3Q+dA1JovTGfEzHkiK8Zk9PnpDYFEJfaUBcaHQfs/e2DiEcnFJhKhCrvUTTPtIH8m4DQINwG32FM1g=}
